<?php
/** @var \Dev\Banner\Block\Template $block */
//echo $block->sayHello();
?>

<!-- <div class="template">
    <h1><?=$block->sayHello()?></h1>
</div> -->
<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}

</style>

<table>
  <tr>
    <th>Banner Id</th>
    <th>Name</th>
    <th >Image</th>
    <th>Status</th>
    <th>Short Description</th>
  </tr>
    <?php
        foreach ($block->getBannerCollection() as $key=>$banner){
            echo '<tr>
                    <td>'.$banner->getBannerId().'</td>
                    <td>'.$banner->getName().'</td>
                    <td>'.$banner->getImage().'</td>
                    <td>'.$banner->getStatus().'</td>
                    <td>'.$banner->getShortDescription().'</td>
                  </tr>';
        }
    ?>
</table>

</body>
</html>